package pl.edu.wat.msk;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class Message {

  private String body;

  private double time;

  public Message(String body, double time) {
  }

  public String getBody() {
  return null;
  }

  public double getTime() {
  return 0.0;
  }

}