package pl.edu.wat.msk;

import java.util.Vector;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class MessagesManager {

	private Vector messages;
	
	public void clear() {
	}
	
	public void add(Message message) {
	}
	
	public Vector getMessages() {
		  return null;
	}

}