package pl.edu.wat.msk;

import pl.edu.wat.msk.elements.IModelComponent;
import dissimlab.simcore.SimManager;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class SimulationModel {

  private java.util.Vector<IModelComponent> components;

  /** 
   *  Udost?pnia interfejs do sterowania symulacj?
   */
  private SimManager simManager;

  public void run() {
  }

  public void pause() {
  }

  public void stop() {
  }

  /** 
   *  Metoda uruchamiana tu? przed pr?b? uruchomienia modelu. Je?li znajd? si? b??dy - nie mo?na uruchomi? proces?w.
   */
  public void modelValidate() {
  }

}