package pl.edu.wat.msk.elements;

import java.util.Vector;

import pl.edu.wat.msk.Notification;

/** 
 *  Aby uruchomi? z?o?on? aktywno?? konieczne jest przechowywanie przez niego komponentu ?r?d?a oraz celu.
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class CompositeActivity extends HavePrevNext {

  public java.util.Vector modelComponents;

	@Override
	public IModelComponent getNext() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setNext(IModelComponent next) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public IModelComponent getPrev() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setPrev(IModelComponent prev) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public Vector validate() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void processing(Notification notification) {
		// TODO Auto-generated method stub
		
	}

}