package pl.edu.wat.msk.elements;

import java.util.Vector;

import pl.edu.wat.msk.Notification;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class Destination extends HaveNext {

	public Destination() {
	}
	
	public Destination(IModelComponent next) {
	}

	@Override
	public IModelComponent getNext() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setNext(IModelComponent next) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public Vector validate() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void processing(Notification notification) {
		// TODO Auto-generated method stub
		
	}

}