package pl.edu.wat.msk.elements;

import java.util.ArrayList;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public abstract class HavePrev implements IHavePrev {

	protected ArrayList<IModelComponent> prev;
	
	public HavePrev() {
		prev = new ArrayList<>();
	}

	public ArrayList<IModelComponent> getPrev() {
		return prev;
	}
	
	public void setPrev(ArrayList<IModelComponent> prev) {
		this.prev = prev;
	}

	public void addPrev(IModelComponent prev) {
		this.prev.add(prev);
	}
	
	public void removePrev(IModelComponent prev) {
		this.prev.remove(prev);
	}
}