package pl.edu.wat.msk.elements;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public abstract class HaveNext extends ModelComponent implements IHaveNext {

	public IModelComponent next;

}