package pl.edu.wat.msk.elements;

import java.util.ArrayList;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public abstract class HavePrevNext extends ModelComponent implements IHaveNext, IHavePrev {

	protected ArrayList<IModelComponent> nexts;
	
	protected ArrayList<IModelComponent> prevs;
	
	
	public HavePrevNext() {
		nexts = new ArrayList<>();
		prevs = new ArrayList<>();
	}

	public ArrayList<IModelComponent> getPrev() {
		return prevs;
	}
	
	public void setPrev(ArrayList<IModelComponent> prev) {
		this.prevs = prev;
	}

	public void addPrev(IModelComponent prev) {
		this.prevs.add(prev);
	}
	
	public void removePrev(IModelComponent prev) {
		this.prevs.remove(prev);
	}

	public ArrayList<IModelComponent> getNext() {
		return nexts;
	}
	
	public void setNext(ArrayList<IModelComponent> next) {
		nexts = next;
	}

	public void addNext(IModelComponent next) {
		nexts.add(next);
	}
	
	public void removeNext(IModelComponent next) {
		nexts.remove(next);
	}
}