package pl.edu.wat.msk.elements;

import java.util.ArrayList;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public abstract class HaveNext extends ModelComponent implements IHaveNext {

	protected ArrayList<IModelComponent> nexts;
	
	public HaveNext() {
		nexts = new ArrayList<>();
	}

	public ArrayList<IModelComponent> getNext() {
		return nexts;
	}
	
	public void setNext(ArrayList<IModelComponent> next) {
		nexts = next;
	}

	public void addNext(IModelComponent next) {
		nexts.add(next);
	}
	
	public void removeNext(IModelComponent next) {
		nexts.remove(next);
	}
}