package pl.edu.wat.msk.elements;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public abstract class HavePrevNext extends ModelComponent implements IHaveNext, IHavePrev {

	public IModelComponent next;
	
	public IModelComponent prev;

}