package pl.edu.wat.msk.elements;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public interface IHaveNext {

	public IModelComponent getNext();
	
	public void setNext(IModelComponent next);

}