package pl.edu.wat.msk.elements;

import java.util.ArrayList;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public interface IHavePrev {

	public ArrayList<IModelComponent> getPrev();
	
	public void setPrev(ArrayList<IModelComponent> prev);

	public void addPrev(IModelComponent prev);
	
	public void removePrev(IModelComponent prev);
}