package pl.edu.wat.msk.elements;

import java.util.Vector;

import pl.edu.wat.msk.Notification;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public interface IModelComponent {

	/** 
	 *  Przetwarzanie
	 */
	public void processing(Notification notification);
	
	/** 
	 *  Metoda walidacji komponentu.
	 *  Zwraca kolekcj? ewentualnych problem?w spotykanych przy walidacji
	 */
	public Vector validate();

}