package pl.edu.wat.msk.elements;

import java.util.Vector;

import pl.edu.wat.msk.Notification;

/**
 * Je?li: AND - zg?oszenie przechodzi tylko gdy dojd? z innych wej?? (razem z
 * nimi) OR - przechdzi je?li przejdzie jak tylko dotrze XOR - przechodzi tylko
 * jedno zg?oszenie kt?re dosz?o
 * 
 * Przemy?le? jeszcze jak ogarn?? kilka wej?? i wyj??
 * 
 * @since 24.05.2014, 19:50 Generated by AgroUML
 * 
 */
public class LogicGate extends HavePrevNext {

	@Override
	public Vector<ValidationMessage> validate() {
		Vector<ValidationMessage> msgs = new Vector<>();

		if (this.prevs.isEmpty()) {
			msgs.add(new ValidationMessage(
					"Brak poprzedników dla bramki logicznej",
					"Każda bramka powinna posiadać przynajmniej jeden poprzednik",
					this));
		}

		if (this.nexts.isEmpty()) {
			msgs.add(new ValidationMessage("Brak następników dla bramki logicznej",
					"Każda bramka musi posiadać przynajmniej jeden następnik",
					this));
		}

		return msgs;
	}

	@Override
	public void processing(Notification notification) {
		// TODO Auto-generated method stub

	}
}