package pl.edu.wat.msk.elements;

import dissimlab.simcore.BasicSimObj;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public abstract class ModelComponent extends BasicSimObj implements IModelComponent {

  public String name;

  public String description;

  /** 
   *  Metoda do zaimplementowania
   */
  public abstract void processing();

}