package pl.edu.wat.msk.elements;

import java.util.ArrayList;
import java.util.Vector;

import dissimlab.monitors.MonitoredVar;
import pl.edu.wat.msk.Notification;

/** 
 *  Kolejka zg?osze?
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class Queue extends HavePrevNext implements IHaveNext {

	  private int size;
	
	  private java.util.Vector notifications;
	
	  /** 
	   *  Zminenna monitora czasu oczekiwania w kolejce
	   */
	  public MonitoredVar waitTimeMV;
	
	  /** 
	   *  Zmienna monmitora d?ugo?ci kolejki
	   */
	  public MonitoredVar queueLengthMV;
	
	  public Queue(int size) {
	  }

	  /** 
	   *  Dodanie zg?oszenia do kolejki
	   */
	  public void add(Notification notification) {
	  }
	
	  /** 
	   *  Usuni?cie zg?oszenia z kolejki
	   */
	  public Notification delete() {
	  return null;
	  }
	
	  /** 
	   *  Usuni?cie konkretnego zg?oszenia
	   */
	  public void delete(Notification notification) {
	  }
	
	  /** 
	   *  Liczba zg?osze? w kolejce
	   */
	  public int getCount() {
	  return 0;
	  }
	
	  public int getSize() {
	  return 0;
	  }
	
	@Override
	public Vector validate() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void processing(Notification notification) {
		// TODO Auto-generated method stub
		
	}

}