package pl.edu.wat.msk.elements;

import java.util.Vector;

import dissimlab.simcore.SimEventSemaphore;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class Semaphore extends HavePrevNext implements IHaveNext {

	private SimEventSemaphore semaphore;
	
	public boolean isOpen() {
	return false;
	}

	@Override
	public IModelComponent getPrev() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setPrev(IModelComponent prev) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Vector validate() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public IModelComponent getNext() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void setNext(IModelComponent next) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void processing() {
		// TODO Auto-generated method stub
		
	}

}