package pl.edu.wat.msk.elements;

import java.util.Vector;

import dissimlab.monitors.MonitoredVar;
import pl.edu.wat.msk.distributions.IDistribution;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class SimpleActivity extends HavePrevNext {

	/** 
	 *  liczba jednocze?nie obs?ugiwanych zg?osze?
	 */
	public int simultaneouslyServicedNotifications;
		
	public IDistribution serviceDistribution;
		
	/** 
	 *  Zminenna monitora czasu obs?ugi
	 */
	public MonitoredVar serviceTimeMVC;
		
	public boolean isFree() {
	return false;
	}
		
	public void notificationService() {
	}
		
	public SimpleActivity(IDistribution serviceDistribution) {
	}
		
	public SimpleActivity(int serviceTime) {
	}

	@Override
	public IModelComponent getNext() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setNext(IModelComponent next) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public IModelComponent getPrev() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setPrev(IModelComponent prev) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public Vector validate() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void processing() {
		// TODO Auto-generated method stub
		
	}

}