package pl.edu.wat.msk.elements;

import java.util.Vector;

import dissimlab.monitors.MonitoredVar;
import pl.edu.wat.msk.Notification;
import pl.edu.wat.msk.distributions.IDistribution;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class Source extends HavePrevNext implements IHaveNext {
	
	/** 
	 *  rozk?ad przerw pomi?dzy generowaniem zg?osze?
	 */
	public IDistribution breaksDistribution;
	
	/** 
	 *  rozk?ad liczby generowanych zg?osze? jednocze?nie
	 */
	public IDistribution generateDistribution;
	
	/** 
	 *  Czas generowania zg?osze? ( w sekundach ). Je?li 0 sek to decyduje liczba zg?osze? do wygenerowania.
	 */
	public int generateTime;
	
	public MonitoredVar durningNotificationTimeMV;
	
	public Source(IModelComponent next, IDistribution breaksDistribution, IDistribution generateDistribution) {
	}
	
	/** 
	 *  Konstruktor wykorzystywany do zastosowania obiektu wewn?trz z?o?onej aktywno?ci. W?wczas obiekt nie generuje zg?osze?, a staje si? po?rednikiem prekazuj?cym dalej zg?oszenie, kt?re do niego dotar?o.
	 */
	public Source(IModelComponent next) {
	}
	
	/** 
	 *  Metoda wywo?ywana przez aktywno?? z?o?on?. W celu przekazania zg?oszenia przez ?r?d?o.
	 */
	public void handOver(Notification notification) {
	}

	@Override
	public IModelComponent getPrev() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setPrev(IModelComponent prev) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public Vector validate() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public IModelComponent getNext() {
		// TODO Auto-generated method stub
		return null;
	}
	
	@Override
	public void setNext(IModelComponent next) {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public void processing() {
		// TODO Auto-generated method stub
		
	}

}