package pl.edu.wat.msk.distributions;

import dissimlab.random.SimGenerator;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class AbstractDistribution implements IDistribution {

  /** 
   *  Wykorzystywany do generowania liczb pseudolosowych
   */
	private SimGenerator simGen;

	@Override
	public double getNextDouble() {
		// TODO Auto-generated method stub
		return 0;
	}

}