package pl.edu.wat.msk.distributions;

import dissimlab.random.SimGenerator;

/**
 * 
 * @since 24.05.2014, 19:50 Generated by AgroUML
 * 
 */
public abstract class AbstractDistribution implements IDistribution {

	/**
	 * Wykorzystywany do generowania liczb pseudolosowych
	 */
	private SimGenerator simGen;
	
	public AbstractDistribution() {
		this.simGen = new SimGenerator();
	}

	public SimGenerator getSimGen() {
		return simGen;
	}

	public void setSimGen(SimGenerator simGen) {
		this.simGen = simGen;
	}

}