package pl.edu.wat.msk.distributions;

/**
 * 
 * @since 24.05.2014, 19:50 Generated by AgroUML
 * 
 */
public class Laplace extends AbstractDistribution {

	public double a;

	public Laplace(double a) {
		this.a = a;
	}

	@Override
	public double getNextDouble() {
		return super.getSimGen().laplace(a);
	}

}