package pl.edu.wat.msk.distributions;

/**
 * 
 * @since 24.05.2014, 19:50
 * Generated by AgroUML
 *
 */
public class Normal extends AbstractDistribution {

  public double a;

  public double b;

  public Normal(double a, double b) {
  }

}