//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.07 at 10:43:30 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}otoczenie" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}kolejka" maxOccurs="unbounded"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}bramka" maxOccurs="unbounded"/>
 *           &lt;element ref="{}semafor" maxOccurs="unbounded"/>
 *           &lt;element ref="{}pod-czynnosc" maxOccurs="unbounded"/>
 *           &lt;element ref="{}polaczenie" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otoczenie",
    "kolejka",
    "bramka",
    "semafor",
    "podCzynnosc",
    "polaczenie"
})
@XmlRootElement(name = "czynnosc")
public class Czynnosc {

    protected List<Otoczenie> otoczenie;
    @XmlElement(required = true)
    protected List<Kolejka> kolejka;
    protected List<Bramka> bramka;
    protected List<Semafor> semafor;
    @XmlElement(name = "pod-czynnosc")
    protected List<PodCzynnosc> podCzynnosc;
    protected List<Polaczenie> polaczenie;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;

    /**
     * Gets the value of the otoczenie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otoczenie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtoczenie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Otoczenie }
     * 
     * 
     */
    public List<Otoczenie> getOtoczenie() {
        if (otoczenie == null) {
            otoczenie = new ArrayList<Otoczenie>();
        }
        return this.otoczenie;
    }

    /**
     * Gets the value of the kolejka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kolejka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKolejka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kolejka }
     * 
     * 
     */
    public List<Kolejka> getKolejka() {
        if (kolejka == null) {
            kolejka = new ArrayList<Kolejka>();
        }
        return this.kolejka;
    }

    /**
     * Gets the value of the bramka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bramka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBramka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bramka }
     * 
     * 
     */
    public List<Bramka> getBramka() {
        if (bramka == null) {
            bramka = new ArrayList<Bramka>();
        }
        return this.bramka;
    }

    /**
     * Gets the value of the semafor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the semafor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSemafor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Semafor }
     * 
     * 
     */
    public List<Semafor> getSemafor() {
        if (semafor == null) {
            semafor = new ArrayList<Semafor>();
        }
        return this.semafor;
    }

    /**
     * Gets the value of the podCzynnosc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the podCzynnosc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPodCzynnosc().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PodCzynnosc }
     * 
     * 
     */
    public List<PodCzynnosc> getPodCzynnosc() {
        if (podCzynnosc == null) {
            podCzynnosc = new ArrayList<PodCzynnosc>();
        }
        return this.podCzynnosc;
    }

    /**
     * Gets the value of the polaczenie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polaczenie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolaczenie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Polaczenie }
     * 
     * 
     */
    public List<Polaczenie> getPolaczenie() {
        if (polaczenie == null) {
            polaczenie = new ArrayList<Polaczenie>();
        }
        return this.polaczenie;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
