//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.07 at 02:53:39 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}otoczenie" maxOccurs="unbounded"/>
 *         &lt;element ref="{}kolejka" maxOccurs="unbounded"/>
 *         &lt;element ref="{}bramka"/>
 *         &lt;element ref="{}semafor"/>
 *         &lt;element ref="{}polaczenie" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otoczenie",
    "kolejka",
    "bramka",
    "semafor",
    "polaczenie"
})
@XmlRootElement(name = "czynnosc")
public class Czynnosc {

    @XmlElement(required = true)
    protected List<Otoczenie> otoczenie;
    @XmlElement(required = true)
    protected List<Kolejka> kolejka;
    @XmlElement(required = true)
    protected Bramka bramka;
    @XmlElement(required = true)
    protected Semafor semafor;
    @XmlElement(required = true)
    protected List<Polaczenie> polaczenie;

    /**
     * Gets the value of the otoczenie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otoczenie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtoczenie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Otoczenie }
     * 
     * 
     */
    public List<Otoczenie> getOtoczenie() {
        if (otoczenie == null) {
            otoczenie = new ArrayList<Otoczenie>();
        }
        return this.otoczenie;
    }

    /**
     * Gets the value of the kolejka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kolejka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKolejka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kolejka }
     * 
     * 
     */
    public List<Kolejka> getKolejka() {
        if (kolejka == null) {
            kolejka = new ArrayList<Kolejka>();
        }
        return this.kolejka;
    }

    /**
     * Gets the value of the bramka property.
     * 
     * @return
     *     possible object is
     *     {@link Bramka }
     *     
     */
    public Bramka getBramka() {
        return bramka;
    }

    /**
     * Sets the value of the bramka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bramka }
     *     
     */
    public void setBramka(Bramka value) {
        this.bramka = value;
    }

    /**
     * Gets the value of the semafor property.
     * 
     * @return
     *     possible object is
     *     {@link Semafor }
     *     
     */
    public Semafor getSemafor() {
        return semafor;
    }

    /**
     * Sets the value of the semafor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Semafor }
     *     
     */
    public void setSemafor(Semafor value) {
        this.semafor = value;
    }

    /**
     * Gets the value of the polaczenie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polaczenie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolaczenie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Polaczenie }
     * 
     * 
     */
    public List<Polaczenie> getPolaczenie() {
        if (polaczenie == null) {
            polaczenie = new ArrayList<Polaczenie>();
        }
        return this.polaczenie;
    }

}
