//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.07 at 02:53:39 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}gniazdo"/>
 *         &lt;element ref="{}koniec"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="maxDlugoscKolejki" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="nieskonczona" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gniazdo",
    "koniec"
})
@XmlRootElement(name = "kolejka")
public class Kolejka {

    @XmlElement(required = true)
    protected Gniazdo gniazdo;
    @XmlElement(required = true)
    protected Koniec koniec;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "maxDlugoscKolejki", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String maxDlugoscKolejki;
    @XmlAttribute(name = "nieskonczona", required = true)
    protected boolean nieskonczona;

    /**
     * Gets the value of the gniazdo property.
     * 
     * @return
     *     possible object is
     *     {@link Gniazdo }
     *     
     */
    public Gniazdo getGniazdo() {
        return gniazdo;
    }

    /**
     * Sets the value of the gniazdo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gniazdo }
     *     
     */
    public void setGniazdo(Gniazdo value) {
        this.gniazdo = value;
    }

    /**
     * Gets the value of the koniec property.
     * 
     * @return
     *     possible object is
     *     {@link Koniec }
     *     
     */
    public Koniec getKoniec() {
        return koniec;
    }

    /**
     * Sets the value of the koniec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Koniec }
     *     
     */
    public void setKoniec(Koniec value) {
        this.koniec = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the maxDlugoscKolejki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxDlugoscKolejki() {
        return maxDlugoscKolejki;
    }

    /**
     * Sets the value of the maxDlugoscKolejki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxDlugoscKolejki(String value) {
        this.maxDlugoscKolejki = value;
    }

    /**
     * Gets the value of the nieskonczona property.
     * 
     */
    public boolean isNieskonczona() {
        return nieskonczona;
    }

    /**
     * Sets the value of the nieskonczona property.
     * 
     */
    public void setNieskonczona(boolean value) {
        this.nieskonczona = value;
    }

}
