//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.25 at 11:01:22 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Symulacja }
     * 
     */
    public Symulacja createSymulacja() {
        return new Symulacja();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc }
     * 
     */
    public Symulacja.Czynnosc createSymulacjaCzynnosc() {
        return new Symulacja.Czynnosc();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Kolejka }
     * 
     */
    public Symulacja.Czynnosc.Kolejka createSymulacjaCzynnoscKolejka() {
        return new Symulacja.Czynnosc.Kolejka();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Otoczenie }
     * 
     */
    public Symulacja.Czynnosc.Otoczenie createSymulacjaCzynnoscOtoczenie() {
        return new Symulacja.Czynnosc.Otoczenie();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Otoczenie.Rozklad }
     * 
     */
    public Symulacja.Czynnosc.Otoczenie.Rozklad createSymulacjaCzynnoscOtoczenieRozklad() {
        return new Symulacja.Czynnosc.Otoczenie.Rozklad();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Bramka }
     * 
     */
    public Symulacja.Czynnosc.Bramka createSymulacjaCzynnoscBramka() {
        return new Symulacja.Czynnosc.Bramka();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Semafor }
     * 
     */
    public Symulacja.Czynnosc.Semafor createSymulacjaCzynnoscSemafor() {
        return new Symulacja.Czynnosc.Semafor();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Polaczenie }
     * 
     */
    public Symulacja.Czynnosc.Polaczenie createSymulacjaCzynnoscPolaczenie() {
        return new Symulacja.Czynnosc.Polaczenie();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Kolejka.Gniazdo }
     * 
     */
    public Symulacja.Czynnosc.Kolejka.Gniazdo createSymulacjaCzynnoscKolejkaGniazdo() {
        return new Symulacja.Czynnosc.Kolejka.Gniazdo();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Kolejka.Koniec }
     * 
     */
    public Symulacja.Czynnosc.Kolejka.Koniec createSymulacjaCzynnoscKolejkaKoniec() {
        return new Symulacja.Czynnosc.Kolejka.Koniec();
    }

    /**
     * Create an instance of {@link Symulacja.Czynnosc.Otoczenie.Rozklad.Param }
     * 
     */
    public Symulacja.Czynnosc.Otoczenie.Rozklad.Param createSymulacjaCzynnoscOtoczenieRozkladParam() {
        return new Symulacja.Czynnosc.Otoczenie.Rozklad.Param();
    }

}
