//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.07 at 07:57:12 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kolejka }
     * 
     */
    public Kolejka createKolejka() {
        return new Kolejka();
    }

    /**
     * Create an instance of {@link Gniazdo }
     * 
     */
    public Gniazdo createGniazdo() {
        return new Gniazdo();
    }

    /**
     * Create an instance of {@link Koniec }
     * 
     */
    public Koniec createKoniec() {
        return new Koniec();
    }

    /**
     * Create an instance of {@link PodCzynnosc }
     * 
     */
    public PodCzynnosc createPodCzynnosc() {
        return new PodCzynnosc();
    }

    /**
     * Create an instance of {@link Symulacja }
     * 
     */
    public Symulacja createSymulacja() {
        return new Symulacja();
    }

    /**
     * Create an instance of {@link Czynnosc }
     * 
     */
    public Czynnosc createCzynnosc() {
        return new Czynnosc();
    }

    /**
     * Create an instance of {@link Otoczenie }
     * 
     */
    public Otoczenie createOtoczenie() {
        return new Otoczenie();
    }

    /**
     * Create an instance of {@link Rozklad }
     * 
     */
    public Rozklad createRozklad() {
        return new Rozklad();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Bramka }
     * 
     */
    public Bramka createBramka() {
        return new Bramka();
    }

    /**
     * Create an instance of {@link Semafor }
     * 
     */
    public Semafor createSemafor() {
        return new Semafor();
    }

    /**
     * Create an instance of {@link Polaczenie }
     * 
     */
    public Polaczenie createPolaczenie() {
        return new Polaczenie();
    }

    /**
     * Create an instance of {@link Warunek }
     * 
     */
    public Warunek createWarunek() {
        return new Warunek();
    }

}
