//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.07 at 02:53:39 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}czynnosc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "czynnosc"
})
@XmlRootElement(name = "symulacja")
public class Symulacja {

    @XmlElement(required = true)
    protected Czynnosc czynnosc;

    /**
     * Gets the value of the czynnosc property.
     * 
     * @return
     *     possible object is
     *     {@link Czynnosc }
     *     
     */
    public Czynnosc getCzynnosc() {
        return czynnosc;
    }

    /**
     * Sets the value of the czynnosc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Czynnosc }
     *     
     */
    public void setCzynnosc(Czynnosc value) {
        this.czynnosc = value;
    }

}
