//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.25 at 06:57:30 PM CEST 
//


package pl.edu.wat.wcy.mtsk.xml_elements;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="czynnosc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="otoczenie" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="rozklad">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="param" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="wartosc" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="dlugoscGenerowania" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="maxIloscZgloszen" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="kolejka" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="gniazdo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="koniec">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nieskonczona" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="bramka">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="semafor">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="polaczenie" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="od" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="do" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "czynnosc"
})
@XmlRootElement(name = "symulacja")
public class Symulacja {

    @XmlElement(required = true)
    protected Symulacja.Czynnosc czynnosc;

    /**
     * Gets the value of the czynnosc property.
     * 
     * @return
     *     possible object is
     *     {@link Symulacja.Czynnosc }
     *     
     */
    public Symulacja.Czynnosc getCzynnosc() {
        return czynnosc;
    }

    /**
     * Sets the value of the czynnosc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Symulacja.Czynnosc }
     *     
     */
    public void setCzynnosc(Symulacja.Czynnosc value) {
        this.czynnosc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="otoczenie" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="rozklad">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="param" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="wartosc" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="dlugoscGenerowania" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="maxIloscZgloszen" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="kolejka" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="gniazdo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="koniec">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="nieskonczona" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="bramka">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="semafor">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="polaczenie" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="od" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="do" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "otoczenie",
        "kolejka",
        "bramka",
        "semafor",
        "polaczenie"
    })
    public static class Czynnosc {

        @XmlElement(required = true)
        protected List<Symulacja.Czynnosc.Otoczenie> otoczenie;
        @XmlElement(required = true)
        protected List<Symulacja.Czynnosc.Kolejka> kolejka;
        @XmlElement(required = true)
        protected Symulacja.Czynnosc.Bramka bramka;
        @XmlElement(required = true)
        protected Symulacja.Czynnosc.Semafor semafor;
        @XmlElement(required = true)
        protected List<Symulacja.Czynnosc.Polaczenie> polaczenie;

        /**
         * Gets the value of the otoczenie property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otoczenie property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOtoczenie().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Symulacja.Czynnosc.Otoczenie }
         * 
         * 
         */
        public List<Symulacja.Czynnosc.Otoczenie> getOtoczenie() {
            if (otoczenie == null) {
                otoczenie = new ArrayList<Symulacja.Czynnosc.Otoczenie>();
            }
            return this.otoczenie;
        }

        /**
         * Gets the value of the kolejka property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the kolejka property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKolejka().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Symulacja.Czynnosc.Kolejka }
         * 
         * 
         */
        public List<Symulacja.Czynnosc.Kolejka> getKolejka() {
            if (kolejka == null) {
                kolejka = new ArrayList<Symulacja.Czynnosc.Kolejka>();
            }
            return this.kolejka;
        }

        /**
         * Gets the value of the bramka property.
         * 
         * @return
         *     possible object is
         *     {@link Symulacja.Czynnosc.Bramka }
         *     
         */
        public Symulacja.Czynnosc.Bramka getBramka() {
            return bramka;
        }

        /**
         * Sets the value of the bramka property.
         * 
         * @param value
         *     allowed object is
         *     {@link Symulacja.Czynnosc.Bramka }
         *     
         */
        public void setBramka(Symulacja.Czynnosc.Bramka value) {
            this.bramka = value;
        }

        /**
         * Gets the value of the semafor property.
         * 
         * @return
         *     possible object is
         *     {@link Symulacja.Czynnosc.Semafor }
         *     
         */
        public Symulacja.Czynnosc.Semafor getSemafor() {
            return semafor;
        }

        /**
         * Sets the value of the semafor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Symulacja.Czynnosc.Semafor }
         *     
         */
        public void setSemafor(Symulacja.Czynnosc.Semafor value) {
            this.semafor = value;
        }

        /**
         * Gets the value of the polaczenie property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the polaczenie property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPolaczenie().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Symulacja.Czynnosc.Polaczenie }
         * 
         * 
         */
        public List<Symulacja.Czynnosc.Polaczenie> getPolaczenie() {
            if (polaczenie == null) {
                polaczenie = new ArrayList<Symulacja.Czynnosc.Polaczenie>();
            }
            return this.polaczenie;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Bramka {

            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "rodzaj")
            protected String rodzaj;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the rodzaj property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRodzaj() {
                return rodzaj;
            }

            /**
             * Sets the value of the rodzaj property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRodzaj(String value) {
                this.rodzaj = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="gniazdo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="koniec">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="nieskonczona" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "gniazdo",
            "koniec"
        })
        public static class Kolejka {

            @XmlElement(required = true)
            protected Symulacja.Czynnosc.Kolejka.Gniazdo gniazdo;
            @XmlElement(required = true)
            protected Symulacja.Czynnosc.Kolejka.Koniec koniec;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "nieskonczona")
            protected Boolean nieskonczona;

            /**
             * Gets the value of the gniazdo property.
             * 
             * @return
             *     possible object is
             *     {@link Symulacja.Czynnosc.Kolejka.Gniazdo }
             *     
             */
            public Symulacja.Czynnosc.Kolejka.Gniazdo getGniazdo() {
                return gniazdo;
            }

            /**
             * Sets the value of the gniazdo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Symulacja.Czynnosc.Kolejka.Gniazdo }
             *     
             */
            public void setGniazdo(Symulacja.Czynnosc.Kolejka.Gniazdo value) {
                this.gniazdo = value;
            }

            /**
             * Gets the value of the koniec property.
             * 
             * @return
             *     possible object is
             *     {@link Symulacja.Czynnosc.Kolejka.Koniec }
             *     
             */
            public Symulacja.Czynnosc.Kolejka.Koniec getKoniec() {
                return koniec;
            }

            /**
             * Sets the value of the koniec property.
             * 
             * @param value
             *     allowed object is
             *     {@link Symulacja.Czynnosc.Kolejka.Koniec }
             *     
             */
            public void setKoniec(Symulacja.Czynnosc.Kolejka.Koniec value) {
                this.koniec = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the nieskonczona property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isNieskonczona() {
                return nieskonczona;
            }

            /**
             * Sets the value of the nieskonczona property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setNieskonczona(Boolean value) {
                this.nieskonczona = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Gniazdo {

                @XmlAttribute(name = "id")
                protected String id;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Koniec {

                @XmlAttribute(name = "id")
                protected String id;

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="rozklad">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="param" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="wartosc" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="dlugoscGenerowania" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="maxIloscZgloszen" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rozklad"
        })
        public static class Otoczenie {

            @XmlElement(required = true)
            protected Symulacja.Czynnosc.Otoczenie.Rozklad rozklad;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "dlugoscGenerowania")
            protected String dlugoscGenerowania;
            @XmlAttribute(name = "maxIloscZgloszen")
            protected String maxIloscZgloszen;

            /**
             * Gets the value of the rozklad property.
             * 
             * @return
             *     possible object is
             *     {@link Symulacja.Czynnosc.Otoczenie.Rozklad }
             *     
             */
            public Symulacja.Czynnosc.Otoczenie.Rozklad getRozklad() {
                return rozklad;
            }

            /**
             * Sets the value of the rozklad property.
             * 
             * @param value
             *     allowed object is
             *     {@link Symulacja.Czynnosc.Otoczenie.Rozklad }
             *     
             */
            public void setRozklad(Symulacja.Czynnosc.Otoczenie.Rozklad value) {
                this.rozklad = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the dlugoscGenerowania property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDlugoscGenerowania() {
                return dlugoscGenerowania;
            }

            /**
             * Sets the value of the dlugoscGenerowania property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDlugoscGenerowania(String value) {
                this.dlugoscGenerowania = value;
            }

            /**
             * Gets the value of the maxIloscZgloszen property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxIloscZgloszen() {
                return maxIloscZgloszen;
            }

            /**
             * Sets the value of the maxIloscZgloszen property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxIloscZgloszen(String value) {
                this.maxIloscZgloszen = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="param" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="wartosc" type="{http://www.w3.org/2001/XMLSchema}int" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "param"
            })
            public static class Rozklad {

                @XmlElement(required = true)
                protected List<Symulacja.Czynnosc.Otoczenie.Rozklad.Param> param;
                @XmlAttribute(name = "id")
                protected String id;
                @XmlAttribute(name = "rodzaj")
                protected String rodzaj;

                /**
                 * Gets the value of the param property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the param property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getParam().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Symulacja.Czynnosc.Otoczenie.Rozklad.Param }
                 * 
                 * 
                 */
                public List<Symulacja.Czynnosc.Otoczenie.Rozklad.Param> getParam() {
                    if (param == null) {
                        param = new ArrayList<Symulacja.Czynnosc.Otoczenie.Rozklad.Param>();
                    }
                    return this.param;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the rodzaj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRodzaj() {
                    return rodzaj;
                }

                /**
                 * Sets the value of the rodzaj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRodzaj(String value) {
                    this.rodzaj = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="wartosc" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Param {

                    @XmlAttribute(name = "nazwa")
                    protected String nazwa;
                    @XmlAttribute(name = "wartosc")
                    protected Integer wartosc;

                    /**
                     * Gets the value of the nazwa property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNazwa() {
                        return nazwa;
                    }

                    /**
                     * Sets the value of the nazwa property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNazwa(String value) {
                        this.nazwa = value;
                    }

                    /**
                     * Gets the value of the wartosc property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getWartosc() {
                        return wartosc;
                    }

                    /**
                     * Sets the value of the wartosc property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setWartosc(Integer value) {
                        this.wartosc = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="od" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="do" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Polaczenie {

            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "od")
            protected String od;
            @XmlAttribute(name = "do")
            protected String _do;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the od property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOd() {
                return od;
            }

            /**
             * Sets the value of the od property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOd(String value) {
                this.od = value;
            }

            /**
             * Gets the value of the do property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDo() {
                return _do;
            }

            /**
             * Sets the value of the do property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDo(String value) {
                this._do = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Semafor {

            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
